# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-03 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlparser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlproperties',
            old_name='about_me',
            new_name='html_source',
        ),
    ]
