# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlparser', '0002_auto_20170603_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlproperties',
            name='html_source',
            field=models.CharField(max_length=10),
        ),
    ]
