# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlparser', '0003_auto_20170603_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlproperties',
            name='html_source',
            field=models.TextField(),
        ),
    ]
