# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-03 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlparser', '0005_auto_20170603_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Html_Content',
            new_name='HtmlContent',
        ),
    ]
