# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlparser', '0006_auto_20170603_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlproperties',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
